import { create } from "zustand"
import { immer } from "zustand/middleware/immer"
import type * as monaco from "monaco-editor"
import {
  RULES,
  PRESETS,
  REQUIRED_CATEGORIES,
  type RuleCategory,
  type PresetName,
} from "@/grammar/rules"
import { buildParser, type BuiltParser } from "@/grammar/ebnf/parser"
import type { ParseResult, ParseError } from "@/grammar/types"
import { collectTerminals, tokenizeDsl } from "@/grammar/dsl/tokenizer"
import { validateDsl } from "@/grammar/dsl/validator"
import { generateFromRule } from "@/grammar/dsl/generator"
/*
  Zustand store for holding the state of the application.

  Responsibilities:
    - Stores the current state of the application, including:
      - The content of the BNF editor
      - The content of the DSL editor
      - The set of active grammar rule IDs
      - The content of CST and AST produced by the parser
      - The currently selected DSL rule for validation/generation
      - The visibility of various panels in the UI
      - References to the Monaco editor instances and callbacks for highlighting/selecting code ranges
    - Enforce conflict resolution and required-category invariants when toggling
    - Rebuild the parser only when active rules change
    - Run the parser (debounced) whenever editor content changes
    - Expose the CST, AST, and rule index to the rest of the app
*/


// ----------------------------------------------------------------------
// STRUCTURES - Types and interfaces for the app state
// ----------------------------------------------------------------------

// code ranges for highlighting and error reporting
export interface CodeRange {
  startLine: number
  startColumn: number
  endLine: number
  endColumn: number
}


// ----------------------------------------------------------------------
// STATE DEFINITION
// ----------------------------------------------------------------------
export interface AppState {
  // --- Editor content -------------------------------------------------------
  bnfCode: string
  dslCode: string
  // --- Active grammar rules -------------------------------------------------
  activeRuleIds: string[]
  activePreset: PresetName | "custom"
  // --- Parse result ---------------------------------------------------------
  parseResult: ParseResult | null
  noErrorParseResult: ParseResult | null
  isParseResultMatching: boolean
  // --- DSL state ------------------------------------------------------------
  selectedDslRule: string
  dslErrors: ParseError[]
  autoGenerateDsl: boolean
  // --- UI state -------------------------------------------------------------
  showSecondEditorPanel: boolean
  showReferencePanel: boolean
  showParseTreePanel: boolean
  showRailroadPanel: boolean

  showParseResultMismatchOverlay: boolean

  // --- Actions --------------------------------------------------------------
  setBNFCode: (code: string) => void
  setDSLCode: (code: string) => void
  setSelectedDslRule: (ruleName: string) => void
  runDslValidation: () => void
  generateDsl: () => string | null
  setAutoGenerateDsl: (v: boolean) => void

  toggleRule: (ruleId: string) => { ok: boolean; reason?: string; changes: string[] }
  selectPreset: (preset: PresetName) => void
  runParse: () => void

  toggleSecondEditorPanel: () => void
  setSecondEditorPanel: (v: boolean) => void
  toggleReferencePanel: () => void
  setReferencePanel: (v: boolean) => void
  toggleParseTreePanel: () => void
  setParseTreePanel: (v: boolean) => void
  toggleRailroadPanel: () => void
  setRailroadPanel: (v: boolean) => void

  toggleParseResultMismatchOverlay: () => void
  setParseResultMismatchOverlay: (v: boolean) => void

  registerEditor: (editor: monaco.editor.IStandaloneCodeEditor) => void
  highlight: (range: CodeRange) => void
  select: (range: CodeRange) => void

  // --- Monaco editor refs ---------------------------------------------------
  ebnfEditor: monaco.editor.IStandaloneCodeEditor | null
  highlightCallback: ((range: CodeRange) => void) | null
  selectCallback: ((range: CodeRange) => void) | null
}


// ----------------------------------------------------------------------
// STORE STATE
// ----------------------------------------------------------------------

// Initial active rules are set to match the BNF preset.
const INITIAL_RULE_IDS = [...PRESETS.BNF].sort()

export const useAppStore = create<AppState>()(
  immer((set, get) => ({
    bnfCode: '',
    dslCode: "",
    activeRuleIds: INITIAL_RULE_IDS,
    activePreset: "BNF",
    parseResult: null,
    noErrorParseResult: null,
    isParseResultMatching: true,
    selectedDslRule: "auto",
    dslErrors: [],
    autoGenerateDsl: false,
    showSecondEditorPanel: true,
    showReferencePanel: false,
    showParseTreePanel: false,
    showRailroadPanel: true,
    showParseResultMismatchOverlay: true,
    ebnfEditor: null,
    highlightCallback: null,
    selectCallback: null,


    // --- Editor content -----------------------------------------------------
    setBNFCode: (code) => {
      set(s => { s.bnfCode = code })
      if (_parseTimer) clearTimeout(_parseTimer)
      _parseTimer = setTimeout(() => get().runParse(), PARSE_DEBOUNCE_MS)
    },

    setDSLCode: (code) => {
      set(s => { s.dslCode = code })
      if (_dslValidateTimer) clearTimeout(_dslValidateTimer)
      _dslValidateTimer = setTimeout(() => get().runDslValidation(), DSL_VALIDATE_DEBOUNCE_MS)
    },

    // --- DSL ----------------------------------------------------------------
    // When the selected DSL rule changes, we may need to re-run validation or generation depending on the autoGenerateDsl setting.
    setSelectedDslRule: (ruleName) => {
      set(s => { s.selectedDslRule = ruleName })
      if (get().autoGenerateDsl) {
        get().generateDsl()
      } else {
        get().runDslValidation()
      }
    },

    // When toggling auto-generate, if turning it on we should immediately generate the DSL for the current entry rule.
    setAutoGenerateDsl: (v) => {
      set(s => { s.autoGenerateDsl = v })
      if (v) get().generateDsl()
    },

    // To validate the DSL
    runDslValidation: () => {
      const { dslCode, parseResult, selectedDslRule } = get()

      if (!parseResult?.ast || parseResult.ast.rules.length === 0) {
        set(s => { s.dslErrors = [] })
        return
      }

      const entryRule = resolveEntryRule(selectedDslRule, parseResult)
      if (!entryRule) {
        set(s => { s.dslErrors = [] })
        return
      }

      if (selectedDslRule !== "auto" && !parseResult.ruleIndex[selectedDslRule]) {
        set(s => { s.selectedDslRule = "auto" })
      }

      if (!dslCode.trim()) {
        set(s => { s.dslErrors = [] })
        return
      }

      const terminals = collectTerminals(parseResult.ast)
      const tokens = tokenizeDsl(dslCode, terminals)
      const result = validateDsl(tokens, parseResult.ast, entryRule)

      set(s => { s.dslErrors = result.errors })
    },

    // To generate the DSL from the currently selected entry rule in the AST.
    generateDsl: () => {
      const { noErrorParseResult, selectedDslRule } = get()

      if (!noErrorParseResult?.ast || noErrorParseResult.ast.rules.length === 0) return null

      const entryRule = resolveEntryRule(selectedDslRule, noErrorParseResult)
      if (!entryRule) return null

      const generated = generateFromRule(noErrorParseResult.ast, entryRule)
      if (generated !== null) {
        set(s => { s.dslCode = generated })
        get().runDslValidation()
      }
      return generated
    },

    // --- Parse --------------------------------------------------------------
    runParse: () => {
      const { bnfCode, activeRuleIds } = get()
      const parseResult = getOrBuildParser(activeRuleIds).parse(bnfCode)
      set(s => { s.parseResult = parseResult })

      if (parseResult.errors.length === 0) {
        set(s => { s.noErrorParseResult = parseResult})
        set(s => { s.isParseResultMatching = true})
      } else {
        set(s => { s.isParseResultMatching = false})
      }

      if (get().autoGenerateDsl) {
        get().generateDsl()
      } else {
        get().runDslValidation()
      }
    },

    // --- Toggle rule --------------------------------------------------------
    toggleRule: (ruleId) => {
      const { activeRuleIds } = get()
      const activeSet = new Set(activeRuleIds)
      const changes: string[] = []

      const rule = RULES[ruleId]
      if (!rule) return { ok: false, reason: `Unknown rule ID: "${ruleId}"`, changes }

      if (activeSet.has(ruleId)) {
        const violated = findViolatedCategories(activeSet, [ruleId], [])
        const fallbacks: string[] = []
        for (const cat of violated) {
          const fb = pickFallback(cat, new Set([ruleId]), new Set())
          if (!fb) {
            return {
              ok: false,
              reason: `Cannot deactivate "${rule.label}" - it is the only active rule in the required category "${cat}" and no fallback is available.`,
              changes,
            }
          }
          fallbacks.push(fb)
        }
        set(s => {
          const next = new Set<string>(s.activeRuleIds)
          next.delete(ruleId)
          changes.push(`- ${ruleId}`)
          for (const fb of fallbacks) {
            if (!next.has(fb)) {
              next.add(fb)
              changes.push(`+ ${fb} (fallback for ${rule.category})`)
            }
          }
          const sorted = [...next].sort()
          s.activeRuleIds = sorted
          s.activePreset = derivePreset(sorted)
        })
        get().runParse()
        return { ok: true, changes }
      }

      const toDeactivate = computeRulesToDeactivate(activeSet, ruleId)
      const toActivate = [ruleId]

      if (ruleId === "nonterminal-spaced" && !activeSet.has("concat-comma")) {
        toActivate.push("concat-comma")
        if (activeSet.has("concat-implicit") && !toDeactivate.includes("concat-implicit")) {
          toDeactivate.push("concat-implicit")
        }
      }

      const violated = findViolatedCategories(activeSet, toDeactivate, toActivate)
      const extraFallbacks: string[] = []
      for (const cat of violated) {
        const fb = pickFallback(cat, new Set(toDeactivate), new Set(toActivate))
        if (!fb) {
          return {
            ok: false,
            reason: `Activating "${rule.label}" would empty required category "${cat}" with no fallback.`,
            changes,
          }
        }
        extraFallbacks.push(fb)
      }

      set(s => {
        const next = new Set<string>(s.activeRuleIds)
        for (const id of toDeactivate) {
          next.delete(id)
          changes.push(`- ${id} (conflict with ${ruleId})`)
        }
        for (const id of toActivate) {
          next.add(id)
          changes.push(`+ ${id}`)
        }
        for (const fb of extraFallbacks) {
          next.add(fb)
          changes.push(`+ ${fb} (fallback)`)
        }
        const sorted = [...next].sort()
        s.activeRuleIds = sorted
        s.activePreset = derivePreset(sorted)
      })

      get().runParse()
      return { ok: true, changes }
    },

    // --- Select preset --------------------------------------------------------
    selectPreset: (preset) => {
      const ids = PRESETS[preset]
      if (!ids) return
      set(s => {
        s.activeRuleIds = [...ids].sort()
        s.activePreset = preset
      })
      get().runParse()
    },

    // --- UI state -------------------------------------------------------------
    toggleSecondEditorPanel: () => set(s => { s.showSecondEditorPanel = !s.showSecondEditorPanel }),
    setSecondEditorPanel:    (v) => set(s => { s.showSecondEditorPanel = v }),
    toggleReferencePanel:    ()  => set(s => { s.showReferencePanel = !s.showReferencePanel }),
    setReferencePanel:       (v) => set(s => { s.showReferencePanel = v }),
    toggleParseTreePanel:    ()  => set(s => { s.showParseTreePanel = !s.showParseTreePanel }),
    setParseTreePanel:       (v) => set(s => { s.showParseTreePanel = v }),
    toggleRailroadPanel:     ()  => set(s => { s.showRailroadPanel = !s.showRailroadPanel }),
    setRailroadPanel:        (v) => set(s => { s.showRailroadPanel = v }),

    toggleParseResultMismatchOverlay:     ()  => set(s => { s.showParseResultMismatchOverlay = !s.showParseResultMismatchOverlay }),
    setParseResultMismatchOverlay:        (v) => set(s => { s.showParseResultMismatchOverlay = v }),
    // --- Monaco ---------------------------------------------------------------
    registerEditor: (editor) => set(s => { s.ebnfEditor = editor }),
    highlight: (range) => get().highlightCallback?.(range),
    select:    (range) => get().selectCallback?.(range),
  })),
)



// ----------------------------------------------------------------------
// HELPER FUNCTIONS
// ----------------------------------------------------------------------

// Given a proposed rule to activate, compute the full set of rules that would need to be deactivated due to conflicts.
function computeRulesToDeactivate(activeIds: Set<string>, incomingId: string): string[] {
  const incoming = RULES[incomingId]
  if (!incoming) return []
  const toDeactivate = new Set<string>()
  for (const cid of incoming.conflicts) {
    if (activeIds.has(cid)) toDeactivate.add(cid)
  }
  for (const activeId of activeIds) {
    if (RULES[activeId]?.conflicts.includes(incomingId)) toDeactivate.add(activeId)
  }
  return [...toDeactivate]
}

// Given a proposed change in active rules, check if any required categories would be left without an active rule. 
// If so, return the list of violated categories.
function findViolatedCategories(
  activeIds: Set<string>,
  toDeactivate: string[],
  toActivate: string[],
): RuleCategory[] {
  const deactivateSet = new Set(toDeactivate)
  const activateSet   = new Set(toActivate)
  const violated: RuleCategory[] = []
  for (const category of REQUIRED_CATEGORIES) {
    const rulesInCategory = Object.values(RULES).filter(r => r.category === category)
    const wouldBeActive = rulesInCategory.filter(
      r => (activeIds.has(r.id) && !deactivateSet.has(r.id)) || activateSet.has(r.id),
    )
    if (wouldBeActive.length === 0) violated.push(category)
  }
  return violated
}

// Given a category that would be left without an active rule, pick a fallback rule from that category to activate. 
// The fallback should not conflict with the incoming rule if possible, but if all rules in the category conflict, just pick the first one.
function pickFallback(
  category: RuleCategory,
  deactivateSet: Set<string>,
  activateSet: Set<string>,
): string | null {
  const candidates = Object.values(RULES).filter(
    r => r.category === category && !deactivateSet.has(r.id) && !activateSet.has(r.id),
  )
  return (
    candidates.find(c => !c.conflicts.some(cid => activateSet.has(cid)))?.id ??
    candidates[0]?.id ??
    null
  )
}

// Given the current set of active rule IDs, determine if they match any of the predefined presets. 
// If so, return the preset name; otherwise return "custom".
function derivePreset(activeIds: string[]): PresetName | "custom" {
  const activeSet = new Set(activeIds)
  for (const [name, ids] of Object.entries(PRESETS) as [PresetName, string[]][]) {
    const presetSet = new Set(ids)
    if (activeSet.size === presetSet.size && [...activeSet].every(id => presetSet.has(id))) {
      return name
    }
  }
  return "custom"
}

// Building the parser is expensive, so we cache it and only rebuild when activeRuleIds changes.
let _cachedParser: BuiltParser | null = null

function getOrBuildParser(activeRuleIds: string[]): BuiltParser {
  const same =
    _cachedParser !== null &&
    _cachedParser.activeRuleIds.length === activeRuleIds.length &&
    _cachedParser.activeRuleIds.every((id, i) => id === activeRuleIds[i])
  if (!same) _cachedParser = buildParser(activeRuleIds)
  return _cachedParser!
}

// We use manual debouncing with timers here instead of a library function 
// because we want the debounce to be shared across multiple calls to the same action 
// (e.g. multiple rapid calls to setBNFCode should result in only one parse), 
// but we don't want the debounce to be shared across different actions 
// (e.g. setBNFCode and setDSLCode should have independent debounces).
let _parseTimer: ReturnType<typeof setTimeout> | null = null
let _dslValidateTimer: ReturnType<typeof setTimeout> | null = null
const PARSE_DEBOUNCE_MS = 250
const DSL_VALIDATE_DEBOUNCE_MS = 300

// Given the currently selected DSL rule and the parse result containing the AST and rule index, 
// determine the actual entry rule to use for validation/generation.
function resolveEntryRule(
  selectedDslRule: string,
  parseResult: ParseResult | null,
): string | null {
  if (!parseResult?.ast || parseResult.ast.rules.length === 0) return null
  if (selectedDslRule === "auto") return parseResult.ast.rules[0].name
  if (parseResult.ruleIndex[selectedDslRule]) return selectedDslRule
  return parseResult.ast.rules[0].name
}



// ----------------------------------------------------------------------
// START FUNCTIONS - functions that should run immediately when the app starts
// ----------------------------------------------------------------------

// Run an initial parse so the UI has a result on first load
setTimeout(() => useAppStore.getState().runParse(), 0)