import { useState, useEffect, useRef, useMemo } from "react"
import Editor from "@monaco-editor/react"
import * as monaco from "monaco-editor"
import { useAppStore } from "@/app/store"
import { buildDslMonarchTokenizer } from "@/components/editor/language/dsl-tokenizer"
import { useTheme } from "@/components/theme-provider"
import { Button } from "../ui/button"
import { Toggle } from "../ui/toggle"
import { FieldLabel } from "../ui/field"
import { Select, SelectTrigger, SelectContent, SelectItem, SelectGroup, SelectLabel, SelectValue } from "../ui/select"
import { Cog } from "lucide-react"
import { registerThemes } from "@/components/editor/language/theme"

export function DSLEditorPanel() {
  const {
    dslCode, setDSLCode, noErrorParseResult,
    selectedDslRule, setSelectedDslRule,
    generateDsl, dslErrors,
    autoGenerateDsl, setAutoGenerateDsl,
  } = useAppStore()
  const { isDark} = useTheme()
  const dslTheme = isDark ? "editor-dark" : "editor-light"
  const LANGUAGE_ID = "dsl"

  const [dslEditor, setDslEditor] = useState<monaco.editor.IStandaloneCodeEditor | null>(null)
  const monacoRef = useRef<typeof monaco | null>(null)

  const ast = noErrorParseResult?.ast ?? null
  const ruleNames = useMemo(() => noErrorParseResult?.ast?.rules.map(r => r.name) ?? [], [noErrorParseResult?.ast])
  const hasGrammarRules = ruleNames.length > 0
  const effectiveRule = useMemo(() => {
    if (selectedDslRule === "auto") return ruleNames[0] ?? null
    return ruleNames.includes(selectedDslRule) ? selectedDslRule : ruleNames[0] ?? null
  }, [selectedDslRule, ruleNames])

  // Switch theme when app theme changes
  useEffect(() => {
    monacoRef.current?.editor.setTheme(dslTheme)
  }, [dslTheme])

  // Tokenizer - fires when editor ready or AST changes
  useEffect(() => {
    if (!dslEditor) return

    if (!monacoRef.current?.languages.getLanguages().some(l => l.id === LANGUAGE_ID)) {
      monacoRef.current?.languages.register({ id: LANGUAGE_ID })
    }

    monacoRef.current?.languages.setMonarchTokensProvider(LANGUAGE_ID, buildDslMonarchTokenizer(ast))
  }, [dslEditor, ast])

  // register language and theme
  function handleBeforeMount(m: typeof monaco) {
    // theme
    registerThemes(m)
    // language
    m.languages.register({ id: LANGUAGE_ID })
  }

  // set up editor instance, theme, language on mount
  function handleMount(editor: monaco.editor.IStandaloneCodeEditor, m: typeof monaco) {
    setDslEditor(editor)
    monacoRef.current = m
    m.editor.setTheme(dslTheme)
    m.editor.setModelLanguage(editor.getModel()!, LANGUAGE_ID)
    m.languages.setMonarchTokensProvider(LANGUAGE_ID, buildDslMonarchTokenizer(ast))

  }

  // markers
  useEffect(() => {
    const m = monacoRef.current
    if (!m || !dslEditor) return
    const model = dslEditor.getModel()
    if (!model) return

    const markers: monaco.editor.IMarkerData[] = dslErrors.map(err => ({
      severity: m.MarkerSeverity.Error,
      message: err.message,
      startLineNumber: err.range.startLine,
      startColumn:     err.range.startColumn,
      endLineNumber:   err.range.endLine,
      endColumn:       err.range.endColumn,
    }))

    m.editor.setModelMarkers(model, "dsl-validator", markers)
  }, [dslEditor, dslErrors])

  return (
    <div className="flex h-full flex-col">
      <div className="flex items-center gap-2 border-b border-border px-3 py-2 shrink-0">
        <FieldLabel className="whitespace-nowrap text-muted-foreground" htmlFor="entry-rule">Entry rule:</FieldLabel>
        <Select onValueChange={value => setSelectedDslRule(value)} disabled={!hasGrammarRules} value={selectedDslRule}>
          <SelectTrigger id="entry-rule" className="min-w-0 max-w-48 w-full cursor-pointer">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectGroup>
              <SelectLabel>RULES</SelectLabel>
              <SelectItem
              className="cursor-pointer"
              value="auto"
              >Auto{effectiveRule ? ` (${effectiveRule})` : ""}</SelectItem>
              {ruleNames.map(name => (
                <SelectItem 
                className="cursor-pointer"
                key={name} value={name}
                >{`<${name}>`}</SelectItem>
              ))}
            </SelectGroup>
          </SelectContent>
        </Select>

        <div className="flex-1" />

        {dslErrors.length > 0 && (
          <span className="text-xs text-destructive font-mono">
            {dslErrors.length} error{dslErrors.length !== 1 ? "s" : ""}
          </span>
        )}

        <div className="flex items-center">
          <Toggle
            variant="outline"
            onClick={() => setAutoGenerateDsl(!autoGenerateDsl)}
            pressed={autoGenerateDsl}
            disabled={!hasGrammarRules}
            title={autoGenerateDsl ? "Auto-generate on: click to disable" : "Auto-generate off: click to enable"}
            className="flex-none cursor-pointer rounded-r-none border-r-0"
          >
            <Cog className={autoGenerateDsl ? "animate-spin" : ""} />
          </Toggle>
          <Button
            variant="outline"
            onClick={generateDsl}
            disabled={!hasGrammarRules}
            title="Generate a random valid string"
            className="cursor-pointer rounded-l-none"
          >
            Generate
          </Button>
        </div>
      </div>

      <div className="flex-1 min-h-0">
        {hasGrammarRules ? (
          <Editor
            value={dslCode}
            beforeMount={handleBeforeMount}
            onMount={handleMount}
            onChange={(value) => { if (value !== undefined) setDSLCode(value) }}
            options={{
              minimap: { enabled: false },
              lineNumbers: "on",
              scrollBeyondLastLine: false,
              wordWrap: "on",
            }}
          />
        ) : (
          <div className="flex h-full items-center justify-center text-sm text-muted-foreground">
            Write a grammar in the EBNF editor to enable the DSL editor
          </div>
        )}
      </div>
    </div>
  )
}