name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - '*'

permissions:
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    # Specify runner +  build & upload the static files as an artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest release
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 25
          cache-dependency-path: live-dsl/package-lock.json
      - name: Debug
        working-directory: live-dsl
        run: |
          node --version
          npm --version
          ls -lha
          pwd
          git show -s
      - name: Install dependencies
        working-directory: live-dsl
        run: |
          npm install || { ls -lha "$HOME/.npm/_logs" && cat $HOME/.npm/_logs/*.log && exit 1; }

      - name: Build static files
        id: build
        working-directory: live-dsl
        run: npm run build

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v5
        with:
          path: live-dsl/dist/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
